= What is it about?
:page-aliases: root, home

This is where I take notes in learning malware development from scratch through Rust (and the windows api).
*This knowledge wiki specifically targets Windows.*
I am not sure about Linux.
I have no idea how to make it work there.


https://maldevacademy.com[MalDev Academy] is a great resource (spoiler alert, it's not free) to learn malware development and I will be using it as my main resource for learning.footnote:[Disclaimer: I may or may not copy-paste stuffs.]
However it heavily focuses on writing C/C++.
Using C/C++ is not bad, I mean, it should be used for learning malware development as foundation if you have no experience.
But I wanted to try using Rust even though I am new to this programming language.

There will be a total of 91 modules (90 if you exclude module 1) in total.
Over time, I will be adding new page for each module that I have finished.
There will be no source repository for the code I have made but I will be adding snippets of code, I think.

For starters, I use the https://microsoft.github.io/windows-docs-rs[rust bindings] of https://learn.microsoft.com/en-us/windows/win32/api[Windows API].
There's also a resource I https://github.com/Whitecat18/Rust-for-Malware-Development[found] that does things in Rust.
